---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
  namespace: default
spec:
  interval: 5m0s
  url: oci://ghcr.io/home-operations/charts/tuppr
  ref:
    tag: 0.3.2
