apiVersion: v1
kind: Secret
metadata:
  name: swiparr-secret
stringData:
  AUTH_SECRET: ENC[AES256_GCM,data:oblE/ioaiks9GRlXmKT1Y+l+TDDO8ff0Q5Dkqa/XJ+N/p4FgN99dm+054Tk=,iv:wd4BHFMfuAX2akri1DgehOTpJxFN9I/HirLoIAaIJrE=,tag:qyImIMJqNEucSmQ4BEw8gQ==,type:str]
  PLEX_TOKEN: ENC[AES256_GCM,data:y9eM2mv1CR9v1VlYOyv0m4hRQMQ=,iv:4ERE71QvfL4IKk7o9I7rGUnLXJxeov1hQXrxeoB33ug=,tag:9njMW9UzN3gBvedBkC+g3Q==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Nm9Qdlp5cnFFM3JVVXlT
        K3RVaUF5NGxYbzlJV3lhQ0UzRWZYWXk4a0g0ClpwbTU4WWxzSEh3dWpSOVRIZUlt
        S1FLM0FmUnVBNHpPZERLaFNlY2FKWVkKLS0tIEwzNGREaFpzVEVvV3pSamxCUVNP
        d1ZWTVdzTkJNQmFPZnlDQ0Z3N0g2aWcK1Jo6G5dGWHOf8iUuu5rpgwRCByYkL0z0
        XHsqotHPOkea9aQ6XBiVe/v+BnP2me7xHdGBeh3HF8o96fYQq3TipQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-07-25T04:36:36Z"
  mac: ENC[AES256_GCM,data:b0yJZxf8AB4oV1oi0B2xA1TzS1XIriF+Vg5jGtGWxvP2jxps5DZWdeGMwPLfv5T5mvw0BAvsDSOUtAmCu7JrtfsXFuRWkH8dFLJlNl1vKrwP9UU/GdmHv1B7vvyA1XUgFaKEYTvMHymc0Xjq3BW+jL7uBBOq30ZX/4PYC+YaSOk=,iv:2HlDguuRA/Sav5sVAgr0VVwBUPxlZswUoG1N4PXCr08=,tag:9Eq7kIAUABUTSKQE25CfLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
