---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-smb
      version: v4.10.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controller.runOnMaster: true