apiVersion: v1
data:
  token: ENC[AES256_GCM,data:/P+f/b2rmVtn5a3Ty8ohxw9Jaww1XOkbuLBD0VMXu+W60oeF+SzmSpLRxmaI6Uo2K2rbl1Xbybw=,iv:hUr73XeGUSaVmi++bKtRKJ8SRnietkWBRFvQTcYSq5Y=,tag:qzxtrp5EDgw7IpOXscV2bQ==,type:str]
kind: Secret
metadata:
  name: forgejo-runner-secret
  namespace: forgejo
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ai9STGJOZS9pQnNBVTdj
        bXVTUnlXcEdib2VmdkszUzhLUjBDWjB2Z2pnCm1PbDRwMUJNYS9nbXQyQk8wQlBJ
        Y016aE1YSFhteVlJMFJNQjF3Z3hNckEKLS0tIC9IWVV2Ykt6NUhIMzAvanpSMFE3
        T1RmS2RpeUJSVkVFcU54UWRsNHljSW8K5SULu+3dgceFdvi3xYcHZ65UialQOxBY
        bRBR4wZMmCK9ZEb7Zjr1iPU1tk+ncwsw9nedFsPIDBKNnG5S/RaI1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-18T11:32:48Z"
  mac: ENC[AES256_GCM,data:5q2bYJsKMkSgliK1QAlZ7T3YyqgjjTov15hDejS9eJJLEv445GVwHVJTQZ7nvLSnd2lvYI/1erVlBZKZgF4FGDvoSwRBe8wPfIDusC/aDIQxVC2INwq1wlTV0L6EDuXSJgsEbcpIi7xs7iraz3u7PbzkvhD/OjOx4gnXQd6wcSk=,iv:3Z0lhIAEDOhwkKSR20ij8hKjGFn5fD4Ze9jqZjIA0II=,tag:qEyUAamUBLej4CYHIt5DmA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
