apiVersion: v1
data:
    token: ENC[AES256_GCM,data:eZRjolorRhuZGk7QgJj2BMC4iFBct2OYiYc4Q98x8MAY8U8N+E/ee1bPulKmwyUUuedrP8N6z3A=,iv:q0OsA4sY7sgwDiF9pMgA/9m/rsbjKlMGZBNN0JdMSho=,tag:586RIuZ5WtZpjN2EQVZW2g==,type:str]
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo
sops:
    age:
        - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ai9STGJOZS9pQnNBVTdj
            bXVTUnlXcEdib2VmdkszUzhLUjBDWjB2Z2pnCm1PbDRwMUJNYS9nbXQyQk8wQlBJ
            Y016aE1YSFhteVlJMFJNQjF3Z3hNckEKLS0tIC9IWVV2Ykt6NUhIMzAvanpSMFE3
            T1RmS2RpeUJSVkVFcU54UWRsNHljSW8K5SULu+3dgceFdvi3xYcHZ65UialQOxBY
            bRBR4wZMmCK9ZEb7Zjr1iPU1tk+ncwsw9nedFsPIDBKNnG5S/RaI1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-18T11:53:29Z"
    mac: ENC[AES256_GCM,data:aP+oOm2kg69/uglIqcxCwgmhAiuyuROmr6TS/ck+wM6D3JdjHmCAYqSrP8+uHooabPZbbtgL/p6LycpR6GMchLegCtjjobU4n8JwFMotddyUvuRNGPWCmtxJ/bX34jsUpgC/v7U5tQcXpbu0TfX/YKqjNHzq7N0coQbbcxSYQno=,iv:GdegD3bbo5j8nVytVg9RFLSMMRec5mzXO6BlJFBqSB8=,tag:qe9Sr6BhQHJicDSPnnAv5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
