# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: forgejo
stringData:
    email: ENC[AES256_GCM,data:a1FyFxIy/O6GyxtgG7z6eBNzHWWqjBQ=,iv:qzQNRbrNqbI9hIbfnxoXKft3sB+F/81XV8rKOC+3Ios=,tag:VKqK+aP7qCnTnVfbYgKBXw==,type:str]
    password: ENC[AES256_GCM,data:6rc4eWAVh/3sIYSjjzfBboNmzlEJkYbP/lNCBoVqohgSygoO8n0HgQ==,iv:noSocDAjt6txOaFSHlDqBy8oQj0G1pzQ8xvofgM/jxU=,tag:+SJuWbAfQn6TuKXzB2kqyA==,type:str]
    username: ENC[AES256_GCM,data:dl8gwQ==,iv:TIvXaBN/AOV4ZFRzykSZ13OgxusJ7/v46chGiJnldIA=,tag:3mcTdLMm2ieh0dgLv4BYog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcm1QdXcvSW4vd3BFSjE0
            OExLYmpzVDhkeE1hMG5kWG5nc05uckRuWjM0CnB3VFVGcnNSdENtUmlVbW9mSTVl
            OW8vKzNCMHRLeWNwZW1FMFdER2NNT28KLS0tIFdZSmR5OTJScnVDUkMwVFNQcGVI
            R3JEVFNxMU51SC9TNGdKUGJJZGpSSlEKKQEVvBC1nnl0orwFdVjMudW0VIgrmK5D
            XsgRn0AYDjQip2O16PNoY+sRJrU75wKAn3Y1LPexisELhya4nRS/cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-06T09:02:03Z"
    mac: ENC[AES256_GCM,data:G05siNE7GU+nFLClE0XnecMNw13ZRtw2fK81W1CR3NWbgMKpeS8MsB4EsWfinCMmsWpamFlnWjlRatdlEBN5pLrIb+korlvJQreHSmXRgANtF4tdDlB3GUqpvSUK/47R3S2na8I/WC/Tlml41GglVrzD92DetPXUshWC2M9PaQI=,iv:HONvOHG3v7p4jNu1SRr87DdAGSO+SEbb94Kc9PUpvg4=,tag:PdoMeOzmFYVgFGoD1R0Nhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
