---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  interval: 30m
  chart:
    spec:
      chart: forgejo
      version: v3.0.0
      sourceRef:
        kind: GitRepository
        name: forgejo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    redis-cluster:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    ingress:
      enabled: true
      className: internal
      hosts:
        - host: git.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "longhorn"
    gitea:
      config:
        database:
          DB_TYPE: sqlite3
        session:
          PROVIDER: db
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
      admin:
        existingSecret: forgejo-admin
        email: finnhartshorn@gmail.com


















    # windmill:
    #   baseDomain: "git.${SECRET_DOMAIN}"
    #   appReplicas: 1
    #   lspReplicas: 1
    #   workerGroups:
    #     - name: "default"
    #       replicas: 1
    #     - name: "native"
    #       replicas: 1
    #   app:
    #     podSecurityContext:
    #       runAsUser: 1000
    #       runAsNonRoot: true
    # ingress:
    #   enabled: true
    #   ingressClassName: internal
    #   host: "git.${SECRET_DOMAIN}"
    #   path: /
    #   pathType: Prefix
