---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 30m
  chart:
    spec:
      chart: .
      version: 3.0.0
      sourceRef:
        kind: OCIRepository
        name: forgejo
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 0
    redis-cluster:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false
    ingress:
      enabled: true
      className: internal
      hosts:
        - host: git.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "longhorn"
    gitea:
      config:
        database:
          DB_TYPE: sqlite3
        session:
          PROVIDER: db
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
      admin:
        existingSecret: forgejo-admin
        email: finnhartshorn@gmail.com
