{
 "title": "Air Quality",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time, value AS \"Finn-office\" FROM homeassistant\nWHERE entity_id = 'alpstuga_air_quality_monitor_carbon_dioxide' AND $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT time, value AS \"Lounge-room\" FROM homeassistant\nWHERE entity_id = 'alpstuga_air_quality_monitor_carbon_dioxide_2' AND $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT time, value AS \"Finn-Office\" FROM homeassistant\nWHERE entity_id = 'alpstuga_air_quality_monitor_pm2_5' AND $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT time, value AS \"Lounge-Room\" FROM homeassistant\nWHERE entity_id = 'alpstuga_air_quality_monitor_pm2_5_2' AND $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT time, value AS \"Main Bedroom\" FROM homeassistant\nWHERE entity_id = 'dyson_w9s_au_saa0686a_pm2_5' AND $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT time, value AS \"Finn-Office\" FROM homeassistant\nWHERE entity_id = 'alpstuga_air_quality_monitor_temperature' AND $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT time, value AS \"Lounge-Room\" FROM homeassistant\nWHERE entity_id = 'alpstuga_air_quality_monitor_temperature_2' AND $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT time, value AS \"Main Bedroom\" FROM homeassistant\nWHERE entity_id = 'dyson_w9s_au_saa0686a_temperature' AND $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT time, value AS \"Finn-Office\" FROM homeassistant\nWHERE entity_id = 'alpstuga_air_quality_monitor_humidity' AND $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT time, value AS \"Lounge-Room\" FROM homeassistant\nWHERE entity_id = 'alpstuga_air_quality_monitor_humidity_2' AND $__timeFilter(time)\nORDER BY time ASC"
    },
    {
     "rawSql": "SELECT time, value AS \"Main Bedroom\" FROM homeassistant\nWHERE entity_id = 'dyson_w9s_au_saa0686a_humidity' AND $__timeFilter(time)\nORDER BY time ASC"
    }
   ]
  }
 ]
}