apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: forgejo
  namespace: flux-system
spec:
  interval: 1m
  url: https://codeberg.org/forgejo-contrib/forgejo-helm.git
  ref:
    branch: main