apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: forgejo
  namespace: flux-system
spec:
  interval: 1m
  url: https://code.forgejo.org/forgejo-helm/forgejo-helm.git
  ref:
    branch: main