# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-db-credentials
  namespace: observability
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:vNr740yKXWc=,iv:EtDxExECNx9KzNAVR5hl//oxl8FLnPnLjjwEyTh66mI=,tag:Trkeir1nGwd9GaYJOtLCrQ==,type:str]
  password: ENC[AES256_GCM,data:ya0NozprL34L9Y2SoOm+EcB1u2eGJJy77wTbjWDM6mjSjAxLZYP1PXP0BY5752uzl31Z880kfvXR67PaY+dHeA==,iv:5NE6l9E0Q/JHQqZ+8E75Q95lu6rIB2xnmPbDaZtiLKE=,tag:BYUB9kYvDhjMkN95wPucqQ==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWWpYNUE4WS9DbDBidG5L
        U1RBOXFoTHk4OGEvWDZDSnliZzZIWnViRm5BCjMzc0pwSC9RVjVoWU1VMTN0Tm5k
        Y283QzRWY28wMkdJTStzUVZSa0MrS0kKLS0tIHMxUXdhbHlRb2FqVUJTWnB6bVpQ
        bHd2eFN3dVMwR2VMemhrZHN5NXZ4YlEKHC8/14SfHMh19+MeMNJEcCUuunJCb2Ry
        u64uZicMijGFk+Ru8OBQD1olrt/cCo1L8gvhDvziP3Y3uqSDQFvB+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-05T07:28:29Z"
  mac: ENC[AES256_GCM,data:EsrDjyPvkdkxszc3l7s9m+J7ray4QgZUU6j5QNDkKL9ujAHfLinneu/Hw+r7KrwYwh1wz897At78iP7BTCmu/3g2zOSf4+9GTVDexEO0m2Vl8sgBHiQboAqzdUm2ToDKB0Ls5qo5u1wkQhYRF5c8SQWOiuqhfk5ujh6Y+TxaPDI=,iv:FCFvBKS//c7YbE/irIvEZI/RzAp+J+Uwp/UbAEBvWMk=,tag:EQL4g24ow59UjczcSncyGg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
