apiVersion: v1
kind: Secret
metadata:
  name: grafana-ro-credentials
  namespace: observability
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:f9coEKJMmIDLtQ==,iv:anCO8DcpByouSHy/7SEVelSip750k7f5lTlEs1Oy3/Q=,tag:bHQZtPjfRxviilq0JqUXxA==,type:str]
  password: ENC[AES256_GCM,data:GD+CSu4EXwiBUR9Xy/0EZcYWKnaHAFVf8vkRDmNKNMjKRo+SM2uocBxhYxY=,iv:/Iw95dXiDhb/ii6I9aucqm9J2YHQCVXTQ3rB6cP3Kts=,tag:ZUuK8Q+AsJbwtO7hpU6QAw==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIemYxeGhvcDBkK1hKSUFw
        NElDK1FsWS9SczhzQUVZL0d5Q0VMN1lpbDJzCjgxakY4dTJHR01kL2VQaDdjK3pv
        Q0xpK1dqbzlreXhPSFdtbkMvY3BEdWMKLS0tIDhXUGN4a3hUVHBBTkE2eitPWENP
        dWIvS2hSZ3VpZGIzdEpWTFhPdVJ1bjQKmzcbrnyfykV94HZMJiOTDPm7toQYS8gD
        mVdz5lj7l0188KjmGwZKrDkWm22QRzTbU+q6zZR9kDBUdGMdODLZBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-06T00:07:29Z"
  mac: ENC[AES256_GCM,data:93ZUAqQzIwLsv9huCe4YPIkCJK8lknbB4Tflcg+phsxsSQRvGQ9xrjTNAamlb2fKoHip5c4mwYTOOnCfaR5D/QktDbutZYp8i9HxRxwVlSbLEU35eo8DC5MIPkcRBCyTaXcL9RbhVRfloKwnX6FGMSfdkSlJIQAZgN2Bvn+iTkg=,iv:PJ1nGgY7Jxuhx3BWty4+HSQY9kSRhzJAbXv/XCLqKRI=,tag:I1O7k+cqygQp4JWp/9Yqfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
