---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: home-assistant
      version: 14.62.0
      sourceRef:
        kind: HelmRepository
        name: andrenarchy
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    env:
      TZ: "Melbourne/Australia"
    persistence:
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
    metrics:
      enabled: true
    ingress:
      main:
        enabled: true
        annotations:
          nginx.org/websocket-services: home-assistant
        ingressClassName: internal
        hosts:
          - host: homeassistant.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
