---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/radarr
              tag: 5.18.4.9674@sha256:f63ab1d9875d81f1b6d7cd69427749451d2fab981e39ffb8d9071c2e21041170
            env:
              TZ: "Australia/Melbourne"
              RADARR__INSTANCE_NAME: Radarr
              RADARR__PORT: &port 7878
              RADARR__APPLICATION_URL: "https://radarr.${SECRET_DOMAIN}"
              RADARR__LOG_LEVEL: info
            resources:
              requests:
                memory: 250Mi
                cpu: 500m
              limits:
                memory: 1500Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
    
    persistence:
      config:
        storageClass: "longhorn"
        accessMode: "ReadWriteOnce"
        size: 1Gi
      videos:
        enabled: true
        existingClaim: "pvc-smb-radarr-movies"
      downloads:
        enabled: true
        existingClaim: "pvc-smb-radarr-downloads"
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        hosts:
        - host: "radarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http