---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-radarr-downloads
  namespace: plex-support
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: samba-share-radarr-downloads  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//${NFS_SERVER}/${NFS_DOWNLOADS}"
    nodeStageSecretRef:
      name: smbcreds
      namespace: flux-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-radarr-downloads
  namespace: plex-support
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-radarr-downloads
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-radarr-movies
  namespace: plex-support
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: samba-share-radarr-movies  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//${NFS_SERVER}/${NFS_MOVIES}"
    nodeStageSecretRef:
      name: smbcreds
      namespace: flux-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-radarr-movies
  namespace: plex-support
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-radarr-movies
  storageClassName: ""
