# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:PB/0h9cDbnPj0sh1Gh2/MeMJfhRAoJ5/BZ9c8FHWnECxt0eq+SpP3zfONj43K8EBCG6tWcH+zfoN2VhNvnBrnpLvm5M+P4C27hfu50aFpTdrpvDWaZ0PF16qgjA0BWTX2p+I,iv:FI8y8HqAeKyLZjBUUH514qErlhvJ456b2JnHdPbFn5w=,tag:ARbp+95XfPjQUJ18ppfvZw==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dkNYYjBSVzBTd0FOekJO
        cEk3VTU5MXNmSEM3aGFpSmVueVVNc1haaW1zClpybGw0QmhjVzdWRUhlcTRUK3N4
        TEN2d1liU2dPYSt1dnFmc2s5eFRla0kKLS0tIFJsb1ZBR1BHcG9UaWNRWFZ1ODky
        Sng1NUdzMnBScUdEZEtNblhweGNpOFkK2oQf8uh8AFx+Chf2RSzCL9mgis18OeOQ
        4RBYdjSZi6Fi5SkGk4G9mA0ig5sL8PcSmiC4xyuA1OnPpnmZ/CE01A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-20T07:00:16Z"
  mac: ENC[AES256_GCM,data:w4roQCKFG/8BrXxW3js6TxVMuoBHsisAEOGVR2AM5rhb4EujNYeJNoOurMfKVYjXFawdRXSYdrpjRUugPZTSH2WPV8Sehin2w8xdNhZR0q7WZ8LAnvzNlu+1TGup5xjNwyPkJTLBoHuG/ZcimiEt6C0iAn4w7clNSxb/wPQfe18=,iv:B0iqGbpvfMinioVwmpVY5SnDm9gVdULfFixUm9D8SRs=,tag:dSPW62Xba9Xijy+lPngcKw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
