# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:XDfrURJbfl/3rN0ZNXaU/UGlKPq7mnofPiasoBuvWyK+YlV+oGI+RhMfJp5CC13Cxw/TTK7vnpCFgpy/0aIBhEmTOJY+9/nmILtTjrGHoUL5g6PSUj1NeYz5F/NEQ6GyQdeh/y3cIg==,iv:C7eiWwhs1HzCpPgTK+ds8VYkRmYk2sy3CToVRp+nrQs=,tag:TsgdxxGKayRPeikRgCekqA==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZWJISzdJMUQxL1cralBQ
        QnBad3VjNkRET3crRjZ2Zzd2ZWJLRVdKVmxjCnRMVXZEL0Zna28zVjI3YndFdzNw
        UFNCdEVkSXdoRzREUUtYblB4WUl1T28KLS0tIHpLb1MzeFA2WFVkQ1BtYmM5aUZp
        MFZrMXJDY1cxSWttVnFPUGd1ckhvUkUK2gS+xziY1+6BvsZPR0uTiMBTBSIl0ubh
        6NY0mllTqrindb9Eo66UE0UjX7l4fjuf+65nPcELc/1qDHIuzVZflg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-23T21:49:16Z"
  mac: ENC[AES256_GCM,data:hCf6Kg547OL89tkawfJgGTxztjKfOvDC5V9m0kuIFIa8gYbP2T1ZgQcyf9BlaLbTVNTL3y4gKVdpsVdz2I9atuOFpZvGiiyaPwFfrb6ZzZH2pnAw24rT4MUriLhyit93yCf+GWR3Yua2xdZMOSsdaJOTQCzPHdCUFdCo0NEa1gc=,iv:icSEdgEblG1KrYiKqr5pGjo8CzyYwWSqOkUf6EU0HC0=,tag:681gkipPK6xbisHYDDd2kA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
