# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:GZgwkbvGGn/sFWCsWfenPU2ggjRHbcYuei6fr//Xsq0yqRE4F252fSBKwK9dG90lF3U8sChj11Y1e5UIYoJfnrJuxeBqSWmNya2T1Ci3LDp+V/McQhRDJU2RIrkBsN2doyOZlCxP1g==,iv:2R4SkjvpITGtJIlXyjXI2i0Bf5s+ZQTa70A2jSwPj6c=,tag:uWgcXP4lZ4h7UUcIFoUP/Q==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeENlU1pMNW12WEVDZjVN
        VzY2TlNRbkgwd0tKM1JickdaMFVZY0d3ZXp3ClZMNjFzZEFjTU5Ob2tUcVRPSnZF
        VHdxMTRvSnowdTY0UUtZRzR2NHN6UHMKLS0tIHc4dWZFcnNYaGVUZnVaUVJUK0RC
        MzZBM0pXTXJKdzhGMFZWd3ZkTlBPc2cK5KiobRTGHpWpOa5cST8S/+2BAU1/X1In
        PklYb1D8DoWSXe3+UtejW5eKdic1H8dtRHg1KBSdmH85441jeGOCBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-23T22:03:36Z"
  mac: ENC[AES256_GCM,data:WYDlQfRctT30xGc6LdE7/1y5O+M3mofPPK7timmSDtOElsYtbPMsx1FxC8MWh/kzvYs/1bF8544Gc3siWRO7qW1yZj/o4d5z+8tmp4tkPmETgr6BV6MrHUayLAcbk0R7Bbc23qFJpOJ1i0N4iHNE82qkXj0O6K7PW7hgVx10txY=,iv:jsjOvspG66aA1nNuUSHeZ/oU3Zh5mP8n9Ac26RgJNgc=,tag:s0c678KF3Gj+XWTU0KT2XQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
