apiVersion: v1
kind: Secret
metadata:
  name: quizzer-db-secret
stringData:
  databaseUrl: ENC[AES256_GCM,data:2HeLeN8JyKjBHhb8E86ypai2/pBv3B7JGXQbDfqd9w/1qBpe5YGHFPjmwmXw59v5fQ/F8d4Uv5jKoD5958QeCGQXlBlvCTYpksgJKdwmXIElcbXv5PAC++F62BjvjAnSRhZ7ZLc6qnd0ejfthvc6J5g=,iv:DVPSo6JPzmdVCgCLeW9BruZJU9DKaAuuTqfItsopRIk=,tag:kk/y8u2da72tKYlIhmlY8w==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZmErSlNWQ002YzZkWkVL
        WnZpMlF0K0VhZU1sOFpzaERVVWRLdklnOFU0CmltdURXalZBYnhjY0lKZG0vRHVz
        c3lFTXBiN0Y2aG9ScUtoZEgxU3ZKTTQKLS0tIDRCbXc2OHdaWjhpbFhYQ0FReG5C
        K29GMTZnUllESkpMMGdVbyt1UW9ZMWcKwbOgVEQ9ayNQD16e2TO50zPZYxXukuMr
        d9GsDoBZ0AD1klyeNkkEieIp9xIDN2iHDcXGFind7o0CY+ZymxKZog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-23T20:45:14Z"
  mac: ENC[AES256_GCM,data:NtI7dTwrZlRZ8Rd3QFNx9YbGMZcyCDPS/uvqaqJfzdbuVZZ08voMw/oM/ycRK1tu3F3pzL4x0wYhuuvWtJvPFIlG9OJfIf3B8Wy3P2vJyionIlJ9dHT0ccT//NYeBeuplOrQ6XJAP+n41nTpMg9BlZW+J+8oMp55pocpM87Nwsg=,iv:2oD2aF6EIFHKTFT3R/Qbry45sGt16pwg2DUg5bh+QJA=,tag:iklXEpLLpa23SYvmY2TEaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
