# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: quizzer-minio-secret
stringData:
  S3_BUCKET: ENC[AES256_GCM,data:btx1TQAmXQ==,iv:wdS01G/anfSi9jxJ7T827xYp24c2uqFmYGnrvlrbyE8=,tag:VgUavJNVELwiJD5Aw8dyaw==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:NPG5brtvVgR5SAWF6LuzEuVRJvO+TWvWoQ==,iv:wqw0/kgvc9y70svFqhhxUOT2oxgzVKSsKBcI0GRXtLQ=,tag:dDa01L3LGrTqTRAsJeVGTg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Y9tVuZWsgMxunw==,iv:A+k3GA13pi+16++/zmeA/ygKjDPCAKO0DigK5esvETc=,tag:w4NDsiWiyCOBK6tMKDl1Xg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:zaT8NbY8XMtFBh77,iv:vi9DbBUceNXbvXouYBTEkO5S4IZYX005hItKErEiT+A=,tag:oE1DMfM1OrsLQLQfu0YWcQ==,type:str]
  AWS_REGION: ENC[AES256_GCM,data:5vC4b/ypGVtT,iv:AjiXttEX5Al5ZGWsDKyZxvspsMH9FpJoOfA3/LoIw30=,tag:GNKe1+dRlTxUjhOLzhPGWA==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVysvSXJDMEZBOTQ3d0RO
        Z2x1VmxGSHFzVlhtL0k0OXB2ZE1xTkVEamxBCnh5TlhmVVY5YnpMYzFxeU10ZE5i
        OCtGd0wvZ3huTXlnQzE0QzU1VExyNVUKLS0tIGg1WTlkRncrNlZ2WnBWMC9KS01T
        U25LQUNIQjN6Zjc5S29ITzFSTitldXcKW+/MJMXv/pXSMGfyVHsKUAxfGTa25wyG
        QKhV32on/fn4SjGzDyomREWimnWwExNemPGFga9gU8oniwArppDsjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-28T11:00:21Z"
  mac: ENC[AES256_GCM,data:LkmpU2vwA/iEHGepuW4TnXY/tRp+NA/dGoV26G/6GtV6pi3/SO7fOM06LMMWK5xtxQRsBd6gI5yP+SPNodeCDYv/EY2eiKkidJQYPbGjrbNEPIhWvU+7x6jf4nWfpeLmU+SVni+ZfgnfNX25Bl1fdMT/9a/Axjt7aXVm7T0Ab9o=,iv:pwOt5Jx7YA0qKERpH7L9TQWeqqYquL6lJcvQX+GHGw4=,tag:yYoD44cBQ7v57gX9lKBykw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
