apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quizzer-quizzes
  namespace: quizzer
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
