---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: arr
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/prowlarr
              tag: 2.1.5.5216@sha256:affb671fa367f4b7029d58f4b7d04e194e887ed6af1cf5a678f3c7aca5caf6ca 
            env:
              TZ: "Australia/Melbourne"
              PROWLARR__INSTANCE_NAME: Prowlarr
              PROWLARR__PORT: &port 9696
              PROWLARR__LOG_LEVEL: info
            resources:
              requests:
                memory: 250Mi
                cpu: 100m
              limits:
                memory: 1500Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
    
    persistence:
      config:
        storageClass: "longhorn"
        accessMode: "ReadWriteOnce"
        size: 1Gi
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        hosts:
        - host: "prowlarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
