---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./windmill/ks.yaml
  - ./forgejo/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: windmill
    target:
      kind: Namespace
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: forgejo
    target:
      kind: Namespace
