apiVersion: v1
kind: Secret
metadata:
  name: grafana-ro-credentials
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:RS2wPzfDNBJSgA==,iv:+1khMWHH/nVTluqAEPBSuJvVQ7IszcBy6REzDx+FAm4=,tag:VHM4INuq+H6Q9lWogt1cKw==,type:str]
  password: ENC[AES256_GCM,data:OberN5iffX4DX28s+d55kOTq4Q9LpSs6TRZr5N3vH7E5eQRs2S/EKuwTKME=,iv:+Fyj7O/lbuNvJRcR8q6BeAz23dCrljP8xud7t7tFRVo=,tag:qrz4wh4yrVIy+I/6A/fB/w==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWG1MaTk2M2RxN2lUQzVm
        VUFRUGI3Q1hQZUJ5ODMxL2lKN0NDNVFHL1VJCm9LNWZJRGJ5cTd4Zm9JWFRKeE5n
        c2JjVFhNWmI5UW0ySE0xaTVHSXFaZkUKLS0tIHc5YjI0cFdCRTRkTlIrTUhvT3k2
        U1ZtSHhBWE9CeHJjRTc5S2VSUzI0eEkK2rgrcb6vG3fMfY773Ty6aPOzfviTKpoT
        tviup58jS1CLqe2dVYwQZpS1JPsL4nkbG0+YQJJ7ifaf7UH9Hf1LGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-05T02:23:43Z"
  mac: ENC[AES256_GCM,data:59fVf6h/Kp8t2ybHZF1RaIa7RqH93QKB7Kf9HOOaw2cosrIn3tqFPLifEHhWyH5zBsBBFAT0poxib1wnHx+dcn8l1pltLAY2DiVf9heQr7Vs690jJUpmLJlXPnrKVT9B9rXGycolMu2kW++qMeml+mRx3xlouTWPwXZpSRtETI0=,iv:m/cUJ3BAfFpyW4uKZuvYCDwuwp0WPbC2/vUnAiEu78A=,tag:RF2d2uHa1tjLAkHvZqaEyw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
