---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./minio-secret.sops.yaml
  - ./windmill-db-credentials.sops.yaml
  - ./quizzer-db-credentials.sops.yaml
  - ./telegraf-db-credentials.sops.yaml
  - ./grafana-ro-credentials.sops.yaml
  - ./postgres-superuser-credentials.sops.yaml
  - ./cluster.yaml
  - ./database-windmill.yaml
  - ./database-quizzer.yaml
  - ./database-telegraf.yaml
  - ./hypertable-maintenance-configmap.yaml
  - ./hypertable-maintenance-cronjob.yaml
  - ./logical-backup-configmap.yaml
  - ./logical-backup-cronjob.yaml
  - ./loadbalancer.yaml
