---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./minio-secret.sops.yaml
  - ./windmill-db-credentials.sops.yaml
  - ./quizzer-db-credentials.sops.yaml
  - ./cluster.yaml
  - ./scheduled-backup.yaml
  - ./database-windmill.yaml
  - ./database-quizzer.yaml
