# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-minio-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:56DOcHhgBtCowmPlZR1+Hzqsv0Q=,iv:Usm7y3urmitAbmlxVGzezWuWxtD7Opa6OlsL5esDypM=,tag:ezXxLRZXUFBElUJVX+3GBg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:YttdDGQI8Uam3QJceILxwce5JCcmu0rJT0TRxF7xhbgqeOp4wBhD3Q==,iv:SaQjCYoRkfDNNifHdfiYuyTLaH46MyyNIlSnuzLaa5I=,tag:uGzsI51oqQJuu/LBzCr9oQ==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYazNXSmdkeEpvODVxN0FF
        Z3R0M0xtN2hvSVM1L3Q3SEpjUmV3NHRjdG1zClRuZUoyK1lEV2VBQUFLTlI0RFVJ
        Q2I0b0FVOFJRN2MvU3dUOXcrNU5LVEkKLS0tIDNRdXdQdUJGWUEzOFZpRUd3Q0Fu
        VEN6WnRWMVNJVWhodHNKZU9EdTJPOUkKuEeVEIOq8x10FmOYsYO+G2P+I9scSkrb
        lWh7PWzWqCz/Go6WPVlR60+fq7FRaTqX20Dmj0L+M2u349mkrJ7/xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T12:00:07Z"
  mac: ENC[AES256_GCM,data:9AisR+PxB4yW+wo37+TAcauO+4YL4lca7985GSXAU9I9s77CGRqdvPW3E+RUx21z7+ZOat574EiCnZFNae+q5oz5YFLDz2jL+zowTJHir4TogC70A0c+eeqAI6Iq6f1DBiS/OD/yY4lmIcSn0gzGZvyNcqp6Sq74qAfv1jxzLx0=,iv:kXHKony0mpjDQ5bwPAvi8LiBjoXbGq44iVI5c3t8+OI=,tag:8Uvkiun3q0ibRFyRK0JHYA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
