apiVersion: v1
kind: Secret
metadata:
  name: postgres-superuser-credentials
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:+ej99YUj8og=,iv:1QowaSzCY/wwZi06t0JAWBxxKJleujcKA0YM6d5UGZ8=,tag:YjZFee8KZ8j4Egs+qHvjVA==,type:str]
  password: ENC[AES256_GCM,data:gtjbX/f19b1WBXgVj5xyjyXTB3aX7lK2kuVhTWjXf58=,iv:JxXH128RWNL+OiO6d4AdU1Hw+M/RWtyQtR2IsFFXdbU=,tag:b+lQ71muz9OTtjWZKhC6Sg==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsck8vcGwzb0szekZGaDZh
        M1oxYjIrQVpVdDAzSFZUSGJ2VzN5OE85dmpzCmdLeS9zSThMa1hpbU1NMjNlVU5F
        N1YwaTB6dzVIaEpoQU9PbXVRZkdEQW8KLS0tIEJ5MlllZDZldVJkWGdRcHRVZUpB
        bjFGZFJkYzRqT09jdWxMdE14dmJpMUkKTjhHz8IV9BxmYRoVqFy2MQwgxJUBlIje
        WFy/ekCQ9P8E6nRgMIXs23DcGme+fhP4uVYz9fWKKSdVIX7kgm37vw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-29T11:16:37Z"
  mac: ENC[AES256_GCM,data:ygdIaGs9UKlEEi8JfUK/HYTolFbXRv5Pj9qdGaB0O7leMA8zTbtbSi6IbQ344BFeQA6cpo8olx4/1naL0aSbqT9I1T+mZSjr++U4xmrNlb0+2mtQPeX2IrdvwH4igi18aMysePVzoQS+Y1Ds7Zcbcnd8q2shaYTI1abp8kI2RkI=,iv:h5CBMO9zICcYKfN2zN3nJls1c1ZgE2JCU7RtgoOP0jk=,tag:GwkSgdvrN+VCctdIbAS25g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
