apiVersion: v1
kind: Secret
metadata:
  name: quizzer-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:oG/QcIwK7Q==,iv:8V4SYgliXKnogd3aYCRuTehec+zuA3h3Ho04j5Rk+mM=,tag:nYe+ncZF6HS0q6V5TANrIg==,type:str]
  password: ENC[AES256_GCM,data:VQja6YfhZl6dlWbS0JTagXNxEuIe8PVKjUFxfrvDzb+iAcGFWZ1roQ==,iv:CqnkAXO82ClIeC1H0GAWVCbgPewRXhhjVeRWaGrSxvY=,tag:9ou+MIqNq+ZRUkSmCP44fA==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRGNOQnZQbWNRcXRpOVpB
        bHJ3TTVydFZleXBRVm92dGhHTW42VmFoVUJrCncxR1lTY0o5TkI4MmtmOVJpbkxh
        aWNPNHJORlhjSktkSjZ1d1BhR2ZyNk0KLS0tIFRScGpYVEEzUm1oQkl0RzFVcE5h
        eW5LZlYwZUdhekFXK1FjcjhZQnVKbjgKWsIbmAf0ITdWyMLNFzyaKCnxcVuckCYQ
        5g/o4YZ2c5Kw7NU4onbWBuJH3qY4SsRN8YMA3w4yFepQgZcJvqqqeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-23T20:45:04Z"
  mac: ENC[AES256_GCM,data:Oi/NeveEBlLjqCyiFKwIxsSbO1eGnbrEMl9UYa1fvvann39LhgSvBH7s2YbQ4fHjBpHpFonQBvGZHLO/Yap1fRYdaDDl1DI0Q5P58JwQjq7S8Kwel5BfCvRlLGfV0FKUcS5BfkMauaVV4WUnHRsLZ2L4NcIFZzgnKnVsAaJBLls=,iv:O777Viq0vWPAVPmSkmZIN5KrNeYeLKH0PBcUMWE1zn0=,tag:zByskk5E4H1eRFd9T2l2zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
