apiVersion: v1
kind: Secret
metadata:
  name: telegraf-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:ZldoslONPJc=,iv:lrmsnJrvXdYg+6OWiYjFxHnKd8gzXzCMuLp3ex0vD2w=,tag:PnL6s+k+KZ5KlvhM2WaIfQ==,type:str]
  password: ENC[AES256_GCM,data:SdlfAXCJDq6B+7FeksiKfhBKBuRg0BUg2uqNO4Y1H/iKBOVSb561TWM8qJQ=,iv:n1uBVYaJNiUpYiCrrBuzxT9GRTYeWTTw8XtKs4xI+eU=,tag:HAVrVCsJq4hPF/FRG6OYpg==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSVpibnNtRWtVbElDNlM0
        aVdadXNXWWZjM1AzUGlIMW9sWHdxVGQ0SjBBCjNLa1Ruc2V5c0dlSmhEWDhxVGxI
        YVR3MGIvVnlXWVMwMFFjVnV5SHNrdGsKLS0tIFdZcU04dC9DWG1lVGV2elVxaW52
        TXBJY2R4Qm1lODVEN3hkMVg4bUZnaEEKB/QZuhEPSkXsJ9TwylQEoseTDSMxPH7c
        zWDbnD9p+rU5M4mtHYD561VSubzTcwcWmov4G+gUT8neDDUGq9J8uQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-05T02:23:43Z"
  mac: ENC[AES256_GCM,data:amSuasTpuVZmpvmw461wmHMzaS7GMN6c6ymZ3IBu7t0QvYHRaVuPj+egxMW4VhC7lB42v4WU4uRJzXkxSDanoo2kcI35N3bdSRh4Qx/CzIGULHqm4HeMMAxthhAqoGWxfYpSQsQNoy81cN28qP4ij1kMzZgmcw/UWQH9NDpmDYk=,iv:ZiFYd9MIhM1dsV4rDo5/xn4oxXTdZ8AWNicKHzKz/oc=,tag:tjmDFc68p/SlqE/AVB4MLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
