apiVersion: v1
kind: Secret
metadata:
  name: telegraf-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:boOis/3Xkrw=,iv:mNeWuaCnf8Q1ylEsGqBQsPGxO5RwBITwtrlaojhmPGs=,tag:invsXImrij208Zd/hiA8xw==,type:str]
  password: ENC[AES256_GCM,data:jLgdI7JVE8Sz61m9jUtwKBh/dYj6KZfdsoftyi7tEuIuwtq5sPID7ZBGYmom2q1cNpkZaxHB2scLIWmYaoha2Q==,iv:YO6+v3dzSf1H0by8LGRiXHNqyM5fI40MeHlxVrfCXTE=,tag:3++d4Du7EfdZF1oYP1E3tA==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnemRLVWZ2K2U4a1N1TTVS
        TW1uQWhucXFBNi95RytQdlkzaFNLaVlnajE0CktrQ2U1L0dyNWd4Mmg1MGRBTmlS
        RHlINWIwN3BoZzZPM0kxTTUzZ0pISFUKLS0tIGordXk2YTVKbFRvd2FrNE8wU0c0
        Vk1XWWNGOXpFWU9XSGN6U29lT1JHeDAKH5OVXCcNFBpTzXQnlmFIYOP1cQMS+VWT
        M1oLxWNvuYkZqUZpbsqVQxPve3mTpwZ0MedFxyfx2Gx9zuHTXTLRuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-05T07:28:29Z"
  mac: ENC[AES256_GCM,data:Tj9Ova1rzMg+1jUiA7P8t7ysBFImfWYE4Rw6ZRXjcJDpiI9zS+WuuJQKlzqMkZqyJ5rIjRBx5HJbNsFLsi95YLWdiLtf0vXy4yFpJHYd1YznqIQgA9B+Y5uae623ArOfml4mKIKvfVMqlK88YQNMirnUfwo96CTLTEXrXDjBxus=,iv:/YICb1gIVFwx12Krn6LfWPm6k9UMEm4w9Yu+K+t+Y6M=,tag:rpqB6UKgYftqS9iGHOK2Og==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
