# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: windmill-db-credentials
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:ZNSoHuBsp6Y=,iv:UqTilLDE/J2J96uMeyergjbsmptH+OtnguGooi1ijUE=,tag:CjVkZ7ZVIPlJThtJJeUa9w==,type:str]
  password: ENC[AES256_GCM,data:o5ahOPx4tuzCoaYlpaMKt1i1s0GrmPEzN+OcsPVIX7Q=,iv:nfByqdsKbVYBlf3hwK2sFsklSDiwOv73xUGNrDxIpKA=,tag:grs/j++LDFoEvto/iEBKbw==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbEZYeWFmZW81ZjMrOVQ0
        Rlk4UWdtMG1sNWdIUzh0WDQ0N3FUZUI2eGdZCkhYWk5jM0NOWFdkL0YrL2ZhVkFr
        U1lZbXhvN2xyazl0OWhzUUE2YURLbncKLS0tIDhMTjhvaWFRL2ZvVWtvbjM0bm5s
        c3JmVFZuT0huelVTOGpIekdiK2dEdm8KOGw67A07J38wE4Nk9ywPkpbp1D7wbmZV
        IRlD5pock0hyDoeCEOFysGmK9eNZ6CsOK74wtz5jeNspwgb8qxkf+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-17T03:27:48Z"
  mac: ENC[AES256_GCM,data:WPNSUfdCrW9GSOXK0T7wyER/RqXw1BV4Gf2Y17Krf8bcb0MktpC3gy94fliaNu23Vy+yiFuwRgEUu6RuGGEd39HWwNqEPWb1oGJX2vouXLHCqJ60xQARAamWrLrtTbxQUi5EdE9mCzjB8ulgB9akb2vjiaw+KluvfZ+ZTaT3KzI=,iv:ZOGsvgdlLxip1wpY9Vy9ySKKhm+5IGl8rvU26pye92g=,tag:J273+1Th4bfcWuo3GomE3A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
