# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: windmill-db-credentials
stringData:
  password: ENC[AES256_GCM,data:RMBlJeRopth/dqpn9ged30C6cTyVupo73bXVNhW9b3A=,iv:AUw7kvhzjBoS3TcrTgAIh/6YPGkDPh8uTbZITHUQZoY=,tag:61bq+mCf4hXvrsJ+UZZxLg==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMGFINTNWYkEvaEROQklr
        M1RqY2I5aENsY3NZNVpYNkFnaU9BUnp5RUVzCjJjZGU0UjIxVnY5SVlzMzlOWnQv
        N1IxaThHdWsxNUd2eGFpMk9XM2xMUXMKLS0tIEthMTA0STFNUHY2Zm9XVmZJMmVt
        NnFVek8wbiszSjRDTmo4NFlHZXBTV1UK/yWI8fsB32ElZDdqYTyau2v6HhZ1W0Td
        aae7EZj+PqbvX8xUFw9MTOk7Ya+fe5PqwctL7RJTw3TMjsdT6jTNFg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T23:03:21Z"
  mac: ENC[AES256_GCM,data:cUbwtj1INmKd0Qbd5TMpX3lA/m1IIN8laehGi2RxjawDDbfCrVhmldlBWXjhuLwo7YTDBp23/GBG8voV+josJ//vLSVIrGrHj/LRGr9OcCGMe+FNexAnehMeTJtviGfdAemJW1BCK16Xu6gVskVqepyNGYfQtAY6XmVcURfaAR4=,iv:y4xgcja9qZXqmCe6Xo9yU/QGj2AFpsyW3CqAnVfdOCM=,tag:RG050aDVe6fdbJK7TkshRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
