---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    monitoring:
        enabled: true
        createPrometheusRules: true
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Delete
      recurringJobSelector:
        enable: false
    ingress:
      enable: true
      ingressClassName: internal
      host: "longhorn.${SECRET_DOMAIN}"
      path: /
      # app:
      #   className: internal
      #   hosts:
      #     - host: &host "longhorn.${SECRET_DOMAIN}"
      #       paths:
      #         - path: /
      #           service:
      #             identifier: app
      #             port: http
      #   tls:
      #     - hosts: [*host]
