# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-minio-secret
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kbaBpDs/D0I=,iv:tIm7Ug2DXJQLh9RiVFYBxhflFEuZskeDJr7KEwSGjvs=,tag:SWJRrmy0OUhcOQQyhaj2/A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:NzKjAhOQGQJFiXz8Irs9QJaLIFYRVZXbviwLRBPD,iv:ngTjK4kAcnTwirT+kUxMEd9bR6IFJMuRD8SYIq7Up8U=,tag:Yygqcu6M5kb3ztvuBIQ0bg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:mnUcqlTp9NEc3UVIQJ+x7BXOzWsHw0XaLA==,iv:P+eRSki+BK/XR580rQYdJojOAJVwKZTA2EEWUVcV8/Q=,tag:eXjPTJMndYXsDT2RU7jXvQ==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYU9sbzJDalNGeTE3WE91
        Rkd4RTdqckEwSzVFKysvWHpFczdGMHVITm5ZCktZdGt2YmZGSmhEWVMwODhZTkpG
        cTcxaUJreU5td3ZDcFMyM054dkhrZ00KLS0tIDhTQ3RzcVNhUnk1SXQvYlpIQ3Nm
        V3Jqa2JBUjNVZWZHRnNaSmRPUThiaGsKTGcrEkjzOqSzXbSQ0pPJjnrkvjOZgJNw
        BhcTfaY1wCwIQj0vWa2B7taE5StMDRNqr8I0q+2Zf2fHlwHkZ9bW2w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-17T11:51:44Z"
  mac: ENC[AES256_GCM,data:jPptu00uNCrQhycsb8ColdNfwj/gmgH2WNSD9EXJMwk179YQEltooAA5nAG5K4oaEYqQ283Jq6I6SHFtm9JR8ZIxjnIivVa9Yz6RfldLrwFqsKnMQgbBeZYX80ByU1JuZ8zYEx+0OxzccfZA5oc60KUAi9rhFBxnjM25mzbw2JM=,iv:TWgb5NqtRVdLY7cGb8oBNgkNVKqkjMA9sBXIxOC5jmM=,tag:UiUw/UHQHF9/cIezGHrfLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
