---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-sonarr-downloads
  namespace: arr
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: samba-share-sonarr-downloads  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//${NFS_SERVER}/${NFS_DOWNLOADS}"
    nodeStageSecretRef:
      name: smbcreds
      namespace: flux-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-sonarr-downloads
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-sonarr-downloads
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-sonarr-tv
  namespace: arr
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: samba-share-sonarr-tv  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: "//${NFS_SERVER}/${NFS_TV}"
    nodeStageSecretRef:
      name: smbcreds
      namespace: flux-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-sonarr-tv
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-sonarr-tv
  storageClassName: ""
