---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
  namespace: adguard
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.107.57@sha256:5c536c1e25f76693ae7ee5e64e8a029893e0f3f1778c8d2a9581383e60cfa9b9
            # env:
            #   TZ: "Australia/Melbourne"
            #   GHIDRA_CERT_PATH: "/opt/ghidra/cert"
            #   GHIDRA_CERT_PASSWORD: ${GHIDRA_CERT_PASSWORD}
            #   HOSTNAME: "ghidra.${SECRET_DOMAIN}"
            resources:
              requests:
                memory: 250Mi
                cpu: 100m
              limits:
                memory: 1500Mi
    persistence:
      adguard-data:
        storageClass: "longhorn"
        accessMode: "ReadWriteOnce"
        size: 100Mi
        globalMounts:
          - path: /opt/adguardhome/work
      adguard-conf:
        storageClass: "longhorn"
        accessMode: "ReadWriteOnce"
        size: 10Mi
        globalMounts:
          - path: /opt/adguardhome/conf
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
          http-initial:
            port: 3000
      dns:
        controller: main
        type: LoadBalancer
        ports:
          port1:
            port: 53
            protocol: UDP
    ingress:
      main:
        enabled: true
        hosts:
        - host: "adguard.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
