---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./tuppr/ks.yaml
  - ./tuppr-watchdog/ks.yaml
  - ./tuppr-log-capture/ks.yaml
  - ./etcd-health-watcher/ks.yaml
components:
  - ../../flux/components/namespace
patches:
  - # Add the name to the namespace
    patch: |
      - op: add
        path: /metadata/name
        value: system-upgrade
    target:
      kind: Namespace
