# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: windmill-db-secret
stringData:
  databaseUrl: ENC[AES256_GCM,data:4bXrFojbB59sJZN+aSJ7DIQniam/ouMdGoul2w3mj81jZKzz3duofaHS9zBh7DzrGb8YToWuh4tDhu+cixZbIVgUkPXxa0OBAc7Qv0IQv64VAXrwYsT3n8I7nSNvYvdFgnxF6g/Wj6VVBqo=,iv:1QXXdliK1d2UgVGsCuFQPHgIp9UmHaKyTv5/Z/uX0YE=,tag:/0cSYGZhWWzYjN5xABUmNQ==,type:str]
sops:
  age:
    - recipient: age13582xjhh7tpn3qsqktzukcdm04cnrn8fw9jhuv647jtqhzd20vaq4xtqe2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZVZsZnF2SUdrbHJJUjdY
        QXpRQUpsVUJGU1RFeFBoTU9IWjV1Q0VQOVZnCkJwYUZ1SUZCS1lsQUNrN3BRVHRk
        YUpwVEo3dVNZZWUzb3loMW9ocC9xTUUKLS0tIE5hQXEydngzUkJ5clltV2ZFb2I2
        TW1kOXRWTW1lWENBbU5jUWNDRmxBS28K1cTUylroYKnkOFDEDdQnfKGx+mcrUdZv
        eE/bUY/tLZZnwVlRhKgbK70L0fWOkpPZmDLaIZclCUXE+En7R2OzhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-16T23:03:21Z"
  mac: ENC[AES256_GCM,data:9eSzCRbvOcbfadWhoPeTrYi+GlA1q09K+HZ0VQJy6kFHqYpq6TBlQsBtRfgYpF5q3N9i9egiloYfCPRpfgYeDv+EgcMlI3ZLJrixX7fWscM1wxx3KWb33QDHAj3k+luQBGq/+6bMzCI1eAAicGKtNOIPh3lypGZoDU3WlpA2bYs=,iv:ToOSsufoQpW7E8amfNozfImIN+yXU4y4L8mZlc7qBR8=,tag:uuPdH8H2eT2Cekq1J1VyZg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
